### PR TITLE
Adding excalidraw plugin

### PR DESCRIPTION
**Pull request by nienow**
Here is my existing 3rd party plugin: https://github.com/nienow/sn-excalidraw

I thought this would be a good plugin to add to the built-in list.

### CODE REVIEW

**Comment by moughxyz** [comment]
@nienow thanks for the submission. I've approved running the CI jobs. Likely some of them will fail. Please take a look at the failures after the run completes.

**Comment by moughxyz** [comment]
Looks like they passed :) Could you add both the author and description field to your package.json?

**Comment by moughxyz** [comment]
Could you also remove any .yarn/cache files, as well as remove changes to the yarn.lock file? I will introduce another commit adding those.

**Comment by nienow** [comment]
I pushed the requested changes. Let me know if there is anything else.

**Pull request merged**
